# Generated by Django 3.2.12 on 2022-04-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220403_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
