# Generated by Django 3.2.12 on 2022-04-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_profiles_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='bio',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
